#@ String(label="Input directory", value="/nrs/hess/data/hess_wafers_60_61/export/zarr_datasets/surface-align/run_20260303_130000/pass00-scale4") inDir
#@ String(label="Output Zarr (.zarr dir)", value="/nrs/hess/data/hess_wafers_60_61/export/zarr_datasets/surface-align/run_20260303_130000/pass00-scale4/combined_faces_3d.zarr") outZarr
#@ String(label="Output dataset name", value="vol") outDataset
#@ Integer(label="Threads", value=8) nThreads

/*
This macro converts a group of zarr 2D surfaces generated by the 76_export_align_view_janelia.sh script
into a single 3D zarr volume that can be more easily reviewed.

To run it in Fiji
  Fiji → File → New → Script… → Language: Groovy
  Paste script, adjust the defaults at the top if you want.
  Click Run.

It was generated by ChatGPT using the following initial prompt:
  I have 90 two dimensional zarr volumes in /nrs/hess/data/hess_wafers_60_61/export/zarr_datasets/surface-align/run_20260303_130000/pass00-scale4
  with names like flat_v2_mb-w61_serial_070_to_079-w61_s070_r00-top-face.zarr, flat_v2_mb-w61_serial_070_to_079-w61_s070_r00-bot-face.zarr,
  flat_v2_mb-w61_serial_070_to_079-w61_s071_r00-bot-face.zarr, ... flat_v2_mb-w61_serial_150_to_159-w61_s158_r00-bot-face.zarr,
  flat_v2_mb-w61_serial_150_to_159-w61_s159_r00-top-face.zarr, flat_v2_mb-w61_serial_150_to_159-w61_s159_r00-bot-face.zarr.
  Each face.zarr directory contains files with names like 0.0 and 17.22.
  I need to combine the two dimensional face volumes into a single three dimensional zarr volume.
  The top face of each two dimensional slab should come before the bot face of the same slab and
  the top face of the next slab should come after the bot face of the previous slab.
  I'd like to use the Fiji ImageJ tool to create the three dimensional zarr volume using a macro.
  Each two dimensional face is large, so I need the macro to create the output zarr first and then do patch writing to save it.

The initial ChatGPT version failed but after a few tweaks, the version below was created and worked.
*/

import java.nio.file.*
import java.util.regex.*
import java.util.concurrent.Executors

import org.janelia.saalfeldlab.n5.DatasetAttributes
import org.janelia.saalfeldlab.n5.DataType
import org.janelia.saalfeldlab.n5.GzipCompression
import org.janelia.saalfeldlab.n5.Compression

import org.janelia.saalfeldlab.n5.zarr.N5ZarrReader
import org.janelia.saalfeldlab.n5.zarr.N5ZarrWriter

import org.janelia.saalfeldlab.n5.imglib2.N5Utils
import net.imglib2.RandomAccessibleInterval
import net.imglib2.view.Views

def p = Paths.get(inDir)
def re = Pattern.compile(/.*-w\d+_s(\d+)_r\d+-(top|bot)-face\.zarr$/)

def faces = []
Files.list(p).forEach { path ->
  def name = path.getFileName().toString()
  def m = re.matcher(name)
  if (m.matches() && Files.isDirectory(path)) {
    def slab = Integer.parseInt(m.group(1))
    def face = m.group(2)
    def faceOrder = (face == "top") ? 0 : 1
    faces << [path: path, slab: slab, face: face, faceOrder: faceOrder, name: name]
  }
}
if (faces.isEmpty()) throw new RuntimeException("No face.zarr dirs found in " + inDir)

faces.sort { a, b ->
  def c = a.slab <=> b.slab
  if (c != 0) return c
  return a.faceOrder <=> b.faceOrder
}
println("Found faces: " + faces.size())

// ---- detect dataset path inside the first zarr container ----
def firstFacePath = faces[0].path.toString()
println("Inspecting: " + firstFacePath)

def in0 = new N5ZarrReader(firstFacePath)

// try root first
String inputDataset = null
if (in0.getDatasetAttributes("") != null) {
  inputDataset = ""
} else {
  def top = in0.list("")
  println("Top-level entries: " + java.util.Arrays.toString(top))
  for (String s : top) {
    if (in0.getDatasetAttributes(s) != null) { inputDataset = s; break }
  }
}
if (inputDataset == null) {
  throw new RuntimeException("No readable dataset found inside " + firstFacePath +
                             " (maybe Zarr v3 or missing zarr backend).")
}
println("Input dataset path: '" + inputDataset + "'")

DatasetAttributes a0 = in0.getDatasetAttributes(inputDataset)
def dims2 = a0.getDimensions()
if (dims2.length != 2) throw new RuntimeException("Expected 2D input; got " + dims2.length + "D")

long x = dims2[0], y = dims2[1], z = faces.size()
long[] outDims = [x, y, z] as long[]
int[] b2 = a0.getBlockSize()
int[] outBlock = [b2[0], b2[1], 1] as int[]

DataType outType = a0.getDataType()
Compression outComp = new GzipCompression()

println("Output dims:  " + java.util.Arrays.toString(outDims))
println("Output block: " + java.util.Arrays.toString(outBlock))
println("Output type:  " + outType)

// ---- create output once ----
def out = new N5ZarrWriter(outZarr)
if (!out.datasetExists(outDataset)) {
  out.createDataset(outDataset, outDims, outBlock, outType, outComp)
}

// ---- patch-write each face ----
def exec = Executors.newFixedThreadPool(Math.max(1, nThreads))

for (int zi = 0; zi < faces.size(); zi++) {
  def f = faces[zi]
  println("Writing z=" + zi + "  " + f.name)

  def inN5 = new N5ZarrReader(f.path.toString())
  RandomAccessibleInterval img2d = N5Utils.open(inN5, inputDataset)

  def img3d = Views.addDimension(img2d, 0, 0)
  def translated = Views.translate(img3d, [0L, 0L, (long)zi] as long[])

  N5Utils.saveRegion(translated, out, outDataset, exec)
}

exec.shutdown()
println("DONE: " + outZarr + " dataset '" + outDataset + "'")