#@ String(label="Input directory (contains *-top-face.zarr / *-bot-face.zarr)", value="/nrs/hess/data/hess_wafers_60_61/export/zarr_datasets/surface-align/run_20260303_130000/pass00-scale4") inDir
#@ Double(label="Scale factor for X and Y (1.0 = no scaling)", value=0.25) scaleXY
#@ Integer(label="Max dimension (if >0, overrides scale factor; scales so max(w,h) <= this)", value=0) maxDim
#@ Integer(label="JPEG quality (0-100)", value=90) jpegQuality

/*
This macro converts a group of zarr 2D surfaces generated by the 76_export_align_view_janelia.sh script
into JPG images that can be imported as a stack.
The stack can then be exported as an AVI for review.

To run it in Fiji
  Fiji → File → New → Script… → Language: Groovy
  Paste script, adjust the defaults at the top if you want.
  Click Run.
*/

import java.nio.file.*
import java.util.regex.*
import org.janelia.saalfeldlab.n5.DatasetAttributes
import org.janelia.saalfeldlab.n5.imglib2.N5Utils
import net.imglib2.RandomAccessibleInterval
import net.imglib2.img.display.imagej.ImageJFunctions
import ij.ImagePlus
import ij.process.ImageProcessor
import javax.imageio.ImageIO
import javax.imageio.stream.ImageOutputStream
import javax.imageio.ImageWriter
import javax.imageio.IIOImage
import javax.imageio.ImageWriteParam

// helper: check for class presence
def hasClass(String fqcn) {
  try { Class.forName(fqcn, false, this.getClass().getClassLoader()); return true }
  catch (Throwable t) { return false }
}

// choose reader factory
def chooseReader() {
  if (hasClass("org.janelia.saalfeldlab.n5.zarr.N5ZarrReader")) {
    println("Detected N5ZarrReader in classpath; will use it.")
    def cls = Class.forName("org.janelia.saalfeldlab.n5.zarr.N5ZarrReader")
    return [type: "zarr", open: { path -> cls.getConstructor(String.class).newInstance(path) }]
  } else if (hasClass("org.janelia.saalfeldlab.n5.N5FSReader")) {
    println("N5ZarrReader not found; using N5FSReader fallback.")
    def cls = Class.forName("org.janelia.saalfeldlab.n5.N5FSReader")
    return [type: "fs", open: { path -> cls.getConstructor(String.class).newInstance(path) }]
  } else {
    throw new RuntimeException("No N5 reader classes found in Fiji. Please enable SaalfeldLab / n5 update-sites.")
  }
}

def findFaces(dir) {
  def re = Pattern.compile(/.*-w\d+_s(\d+)_r\d+-(top|bot)-face\.zarr$/)
  def p = Paths.get(dir)
  if (!Files.isDirectory(p)) throw new RuntimeException("Input directory not found: " + dir)
  def faces = []
  Files.list(p).forEach { path ->
    def name = path.getFileName().toString()
    def m = re.matcher(name)
    if (m.matches() && Files.isDirectory(path)) {
      def slab = Integer.parseInt(m.group(1))
      def face = m.group(2)
      def faceOrder = (face == "top") ? 0 : 1
      faces << [path: path, slab: slab, face: face, faceOrder: faceOrder, name: name]
    }
  }
  faces.sort { a, b ->
    def c = a.slab <=> b.slab
    if (c != 0) return c
    return a.faceOrder <=> b.faceOrder
  }
  return faces
}

def detectDatasetPathFromReader(reader) {
  try {
    if (reader.getDatasetAttributes("") != null) return ""
    def top = reader.list("")
    for (String s : top) {
      if (reader.getDatasetAttributes(s) != null) return s
    }
  } catch (Exception e) {}
  return null
}

def writeJpeg(java.awt.image.BufferedImage bi, File outFile, float quality) {
  Iterator<ImageWriter> writers = ImageIO.getImageWritersByFormatName("jpeg")
  if (!writers.hasNext()) throw new RuntimeException("No JPEG ImageWriter found")
  ImageWriter writer = writers.next()
  ImageWriteParam iwp = writer.getDefaultWriteParam()
  if (iwp.canWriteCompressed()) {
    iwp.setCompressionMode(ImageWriteParam.MODE_EXPLICIT)
    iwp.setCompressionQuality(quality) // 0..1
  }
  ImageOutputStream ios = ImageIO.createImageOutputStream(outFile)
  writer.setOutput(ios)
  try { writer.write(null, new IIOImage(bi, null, null), iwp) }
  finally { ios.close(); writer.dispose() }
}

// ---------- main ----------
def faces = findFaces(inDir)
if (faces.isEmpty()) throw new RuntimeException("No face.zarr directories found in " + inDir)
println("Found faces: " + faces.size() + "  first: " + faces[0].name + " last: " + faces[-1].name)

def readerFactory = chooseReader()
def firstFacePath = faces[0].path.toString()
def reader0 = readerFactory.open(firstFacePath)
def inputDataset = detectDatasetPathFromReader(reader0)

if (inputDataset == null) {
  def p0 = Paths.get(firstFacePath)
  def has_zarray = Files.exists(p0.resolve(".zarray"))
  def has_zarr_json = Files.exists(p0.resolve("zarr.json"))
  def msg = new StringBuilder()
  msg.append("Could not find a readable dataset inside: ").append(firstFacePath).append("\n")
  if (has_zarray) msg.append("Detected .zarray -> Zarr v2 store, but reader couldn't see an array.\n")
  if (has_zarr_json) msg.append("Detected zarr.json -> Zarr v3 store; Fiji N5 plugins often can't read v3.\n")
  msg.append("Try a Fiji build with n5-zarr support, or use Python to write the AVI.\n")
  throw new RuntimeException(msg.toString())
}

println("Using input dataset path: '" + inputDataset + "'")
DatasetAttributes a0 = reader0.getDatasetAttributes(inputDataset)
def dims2 = a0.getDimensions()
if (dims2.length != 2) throw new RuntimeException("Expected 2D faces, got " + dims2.length + "D")
int width0 = (int) dims2[0]
int height0 = (int) dims2[1]
println("Input dims: " + width0 + " x " + height0)

double scale = scaleXY
if (maxDim != null && maxDim > 0) scale = Math.min(1.0, (double)maxDim / Math.max(width0, height0))
int outW = Math.max(1, (int)Math.round(width0 * scale))
int outH = Math.max(1, (int)Math.round(height0 * scale))
println("Output dims: " + outW + " x " + outH + " (scale=" + String.format("%.4f", scale) + ")")

Path tempDir = Files.createTempDirectory("faces_to_avi_jpg_")
println("Writing temporary JPEG frames to: " + tempDir.toString())

int pad = 6
int written = 0
float qualf = Math.max(0.0f, Math.min(1.0f, (float)jpegQuality / 100.0f))

for (int zi = 0; zi < faces.size(); zi++) {
  def f = faces[zi]
  println("Processing frame z=" + zi + "  " + f.name)

  def r = readerFactory.open(f.path.toString())
  RandomAccessibleInterval img2d = N5Utils.open(r, inputDataset)

  ImagePlus imp = ImageJFunctions.wrap(img2d, f.name)
  ImageProcessor ip = imp.getProcessor()

  // ---- FIX: don't call ip.isColor() (not present on ByteProcessor) ----
  int t = imp.getType()
  boolean isRGB = (t == ImagePlus.COLOR_RGB)
  if (!isRGB) {
    if (ip.getBitDepth() != 8) ip = ip.convertToByte(true)  // normalize
  }

  if (outW != imp.getWidth() || outH != imp.getHeight()) {
    ip.setInterpolationMethod(ImageProcessor.BICUBIC)
    ip = ip.resize(outW, outH)
  }

  def bi = ip.getBufferedImage()
  String fname = String.format("frame%0" + pad + "d.jpg", zi + 1)
  File outFile = tempDir.resolve(fname).toFile()
  writeJpeg(bi, outFile, qualf)
  written++

  if ((zi+1) % 50 == 0) println("Wrote " + (zi+1) + " frames...")
}

println("\n" + written + " JPEG frames written to: " + tempDir.toString())
println("import these as a stack: File - Import - Image Sequence...");
println("then save as an API: File - Save As - AVI...")